package model.enums;


public enum GameState {
    SET_PLAYER_NUMBER,
    SET_NAME_AND_TOKEN,
    INITIALIZE_GAME,
    SELECT_STARTINGCARDFACE,
    SELECT_OBJECTIVE,
    PLACING_CARD,
    ADDING_CARD_TO_HAND,
    CHANGING_TURN,
    FINISHED
}
